version: "3.2"
services:
  # MongoDB
  mongodb:
    image: mongo:4.2.8
    ports:
      - 27017:27017
  bibal-backend:
    build: ./bilbal-backend
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
      PORT: 8080
      LOG_LEVEL: debug
      LOG_DIR: ./logs
      MONGO_CONNSTR: mongodb://mongodb:27017
      MONGO_DBNAME: sampleDatabase